[package]
name = "wimg"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["rlib", "cdylib"] # needs to be staticlib when building for e.g. Go

# optimize for small code size
[profile.release]
opt-level = "s"
lto = true

[dependencies]
mozjpeg-sys = { version = "1.0", features = ["unwinding"] }
png = "0.17"
ravif = "0.8"
resize = "0.7"
rgb = "0.8"
thiserror = "1.0"
libwebp-sys2 = { version = "0.1", features = ["1_2", "static"] }
xxhash-rust = { version = "0.8", features = ["const_xxh64"] }

[build-dependencies]
cbindgen = "0.20"

[patch.crates-io]
ravif = { git = "https://github.com/rkusa/cavif-rs.git", branch = "wasi" }
