[package]
name = "mozjpeg"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

# optimize for small code size
[profile.release]
opt-level = "s"
lto = true

[dependencies]
mozjpeg-sys = "1.0"
wee_alloc = "0.4"
