[package]
name = "wimg"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

# optimize for small code size
[profile.release]
opt-level = "s"
lto = true

[dependencies]
mozjpeg-sys = { version = "1.0", features = ["unwinding"] }
resize = "0.7"
rgb = "0.8"

[build-dependencies]
cbindgen = "0.20"
