[workspace]
resolver = "2"
members = [
    "crates/common",
    "crates/jpeg_decode",
    "crates/jpeg_encode",
    "crates/resize",
]

# optimize for small code size
[profile.release]
opt-level = "s"
lto = true
