#!/usr/bin/env sh

# brew install llvm
# brew tap messense/macos-cross-toolchains
# brew install x86_64-unknown-linux-musl
# brew unlink x86_64-unknown-linux-musl

/opt/homebrew/opt/llvm/bin/clang \
    -target x86_64-unknown-linux-musl \
    --sysroot=/opt/homebrew/opt/x86_64-unknown-linux-musl/toolchain/x86_64-unknown-linux-musl/sysroot \
    $@
